### ISSUE TITLE
Devices not showing in the list

### ISSUE THREAD

**Issue by renatochicc** [vanwijkdave/Ainsworth-Issues#1]
Hello,

I have an issue where my bluetooth devices won’t show in the list when I press on Discover Devices,

I tried with a pair of Siberia 840 and a Marley Get Together bluetooth speaker. 

Some assistance pls?

**Comment by vanwijkdave** [comment]
Heya, have you tried following the instructions from the depiction/settings page?

 You can find them here -> [https://daveapps.nl/tweaks/Ainsworth.html](https://daveapps.nl/tweaks/Ainsworth.html)

Let me know if that worked

**Comment by renatochicc** [comment]
Hey,

Managed to add the bluetooth speaker, but whenever it connects to the phone neither of the banners show up. The device is enabled through the settings of the tweak.

**Comment by vanwijkdave** [comment]
Thats weird, what version are you on? (should be 1.0.2)

And when you press on "Test Popup," does it appear at all?

**Comment by renatochicc** [comment]
Weird enough I was on 1.0.1.
Issue is fixed now. Thank you!
