### ISSUE TITLE
Not paring 

### ISSUE THREAD

**Issue by jprice72** [vanwijkdave/Ainsworth-Issues#10]
I have followed the directions tried connecting to Bluetooth then searching tried disconnecting from Bluetooth and searching but nothing works doesn’t show up on the app 
![F3D76272-05F7-4D54-8531-3142F64CA10B](https://user-images.githubusercontent.com/48078295/83366866-b7ea9680-a37f-11ea-8889-c2ea9a957e83.png)
The headphones are plantronics 90 and the iPhone is iPhone X 13.5

**Comment by vanwijkdave** [comment]
Make sure the headphones have been connected to the phone at least once (aka they show up in the bluetooth menu) then hit Start discovering.

Also make sure you're on the latest version!
