### ISSUE TITLE
“License check failed”

### ISSUE THREAD

**Issue by Se7en7NZ** [vanwijkdave/Ainsworth-Issues#11]
I bought the tweak and it says “license failed try again or you didn’t buy the tweak” now how is it possible to not buy the tweak and get it I don’t understand but please help me fix this.

**Comment by ahmadlw** [comment]
Same, I’m having the same issue. I just bought it.

**Comment by ahmadlw** [comment]
It works not though so nevermind

**Comment by vanwijkdave** [comment]
Are you both still having the problem?
First off make sure the device is correctly linked to twickd, since I check there if the product is paid

**Comment by Se7en7NZ** [comment]
Yes I still have the problem what to do???

**Comment by vanwijkdave** [comment]
Is the device's UDID you're using it on correctly linked to your twickd account?

**Comment by Se7en7NZ** [comment]
I’m not sure
