### ISSUE TITLE
Ios 13.5 support

### ISSUE THREAD

**Issue by promethazine-lozenges** [vanwijkdave/Ainsworth-Issues#15]
Not to sure whats going wrong but after installing the tweak the device runs fine but after a certain amount of time the device becomes unresponsive and then resprings its definitely the tweak but when trying to trouble shoot it wont show up on cr4shed what casued the respring so cant really find out whats happing :( |13.5 A13

**Comment by vanwijkdave** [comment]
- Whats the time before it crashes?

- Does it crash when you connect a device or just randomly?

- How are you sure its the tweak? 

-I can't do much without a crashlog

I'm using this tweak myself on iOS 13.5 so, the firmware isn't the issue, please provide a proper bug report. 

Thanks in advance

**Comment by promethazine-lozenges** [comment]
After a resote rootfs the problem stopped happing and i couldn't recreate it i dont have many tweaks and non that would interact with your tweak thanks for confirmation it works on 13.5 it helped me trouble shoot but it was after a device connected and about 10-25 minutes after after an app switch and the device was finished playing the audio of the app opened after the original app it would become laggy and i wouldnt be able to go to the home screen or shut off the device with the power button it might of not been the tweak by itself but i dont have any tweaks that would ￼ interact with yours ￼
