### ISSUE TITLE
Phone freezes when try to connect

### ISSUE THREAD

**Issue by ZamasuandGokuBlack** [vanwijkdave/Ainsworth-Issues#18]
Hey I just bought your tweak Ainsworth and it’s not working... when I go to settings and press add device my phone just blacks out and freezes and resprings.. I went on the website and made an account and registered my device

Here are the logs http://www.mediafire.com/file/sxoo81jyzxng7s9/cydia.log/file
http://www.mediafire.com/file/bwm0g82nat9nt4d/dpkgl.log/file

**Comment by vanwijkdave** [comment]
see https://github.com/vanwijkdave/Ainsworth-Issues/issues/19, if version 1.3.1 still doesn't fix your problem, please let me know
