### ISSUE TITLE
Ainsworth crashes after selecting Add Device 

### ISSUE THREAD

**Issue by punchyouinthenuts** [vanwijkdave/Ainsworth-Issues#19]
As soon as I click _Add Device_ Ainsworth goes to the next screen, displays the _Stop Discovering_ button for a split second before respringing my device. Cr4shed doesn't log the action.

iPhone XS
iOS 13.5
unc0ver 5.3.1
Ainsworth 1.3

**Comment by ZamasuandGokuBlack** [comment]
Same issue please fix it’s been 2 weeks already

**Comment by millearthur** [comment]
Same problem here, any solutions?
Also running iPhone XS

**Comment by vanwijkdave** [comment]
Fixed the issue, it was an compatibility issue with the latest version of libMRYIPC, an update in your package manager should be available < 15 minutes 🙂
