### ISSUE TITLE
AirPods popup broken

### ISSUE THREAD

**Issue by jclgc** [vanwijkdave/Ainsworth-Issues#21]
Having ainsworth installing and enabled somehow breaks the standard AirPods battery popup when opening the case, as well as the share audio popup when trying to share audio with airpods. any fixes?

**Comment by chrismonster13** [comment]
I have the same problem as well. It breaks the SharingViewService unfortunately.

**Comment by vanwijkdave** [comment]
I've found the problem, it will be fixed next update

**Comment by chrismonster13** [comment]
> I've found the problem, it will be fixed next update

You da man 😁

**Comment by vanwijkdave** [comment]
fixed in latest version
