### ISSUE TITLE
Update eror, how to fix

### ISSUE THREAD

**Issue by TyXiu** [vanwijkdave/Ainsworth-Issues#22]
![9C9AA7BC-E8DD-4641-92E5-0050318C4351](https://user-images.githubusercontent.com/73209663/96668222-e5fb6200-1384-11eb-8b2d-9dedc82f222b.png)
How to fix

**Comment by vanwijkdave** [comment]
see https://github.com/vanwijkdave/Ainsworth-Issues/issues/24
