### ISSUE TITLE
pref bundle not loading with device info 

### ISSUE THREAD

**Issue by promethazine-lozenges** [vanwijkdave/Ainsworth-Issues#24]
11 pro ios 13.5 normal unc0ver jailbreak 

Preference bundle not working I have libsparkcolourpicker installed thanks for the hard work

**Comment by lliiiluln** [comment]
![Uploading F281B8B6-0CC6-4C99-93DB-83B7C40C3FFC.jpeg…]()

**Comment by vanwijkdave** [comment]
Fixed! Just update to version 1.4.0.2
