### ISSUE TITLE
Proximity sensor during call not working.

### ISSUE THREAD

**Issue by sportusrcu** [vanwijkdave/Ainsworth-Issues#25]
Iphone 7+ 13.3.1, checkra1n.
Title explains everything, tried to disable all tweaks but problem persists. When i disables anisworth, proximity work like it should.

**Comment by chrismonster13** [comment]
Yes, same issue here. Disabled every tweak except Ainsworth and vice versa and the problem is definetly from Ainsworth tweak.

**Comment by vanwijkdave** [comment]
found the issue, update will be up within a hour :)
