### ISSUE TITLE
cant find my earphone!!

### ISSUE THREAD

**Issue by apple52026** [vanwijkdave/Ainsworth-Issues#3]
i have followed ur guide,  but my device cant appear in the setting, i have been waiting for more than 10 mins, but still the same

**Comment by apple52026** [comment]
i have reinstalled the tweak and still cant discover my device

**Comment by vanwijkdave** [comment]
are you connecting the device without leaving the page? Or are you going to the bluetooth pane to click on your device?

**Comment by apple52026** [comment]
without leaving the page

**Comment by vanwijkdave** [comment]
what iOS are you running? And which phone do you have? Can you also make sure you have libmryipc installed?

**Comment by apple52026** [comment]
1)ios 13.1.1 
2) XR
3) sure, when i chose it, there was three options to choose: remove, reinstall, and hide updates

**Comment by vanwijkdave** [comment]
Try now ;)
