### ISSUE TITLE
Bugs with Custom Colors and Blurred View

### ISSUE THREAD

**Issue by Supernova1114** [vanwijkdave/Ainsworth-Issues#30]
I am really enjoying your tweak but am having a few issues.

**I am in dark mode on iOS 14.0.1, Unc0ver 6.1.1, iPhone XR**
- Tweak list: 

https://imgur.com/a/WeoKWRc

Please tell me if I need to add more info :)

- The modern popup only shows the default colors when custom colors are chosen. The only way to fix this is to pick the default popup (default popup displays correct colors), test popup, pick the modern popup, and test popup. You must do this every time you respring.

- When I enable blurred view, it changes the background color to the default color and blurs not only the background but also the buttons and text. When in blurred mode, it sets all popup views to have the default background color (dark gray).

- Extra info: when opening the custom colors section, the default colors do display for a split second and then switch to the custom colors. 

**Images:**

- I copied the colors from light mode to dark mode, therefore am using custom colors:

![IMG_8372](https://user-images.githubusercontent.com/55326068/120687451-e26da480-c456-11eb-9109-ae8acb53b2a2.jpg)

- Incorrect colors show (even after respring):

![IMG_8373](https://user-images.githubusercontent.com/55326068/120687731-23fe4f80-c457-11eb-82ac-f7a2fcf17aa3.jpg)

- Selecting default popup, then testing, then selecting modern popup once again, then testing, will fix the colors on the modern popup. (Will revert to incorrect colors after respring):

![IMG_8374](https://user-images.githubusercontent.com/55326068/120687887-51e39400-c457-11eb-94a7-9064022d3f4c.jpg)

- 3 Images of blurred view displaying incorrect colors:

![IMG_8375](https://user-images.githubusercontent.com/55326068/120687953-658efa80-c457-11eb-9c4e-d4035316a71a.jpg)
![IMG_8376](https://user-images.githubusercontent.com/55326068/120687962-6889eb00-c457-11eb-806c-67d11e00594e.jpg)
![IMG_8377](https://user-images.githubusercontent.com/55326068/120687973-6aec4500-c457-11eb-90c9-6859c2c5112f.jpg)

**Comment by vanwijkdave** [comment]
Fixed the color updating issue on proximity and pencil view

**Comment by vanwijkdave** [comment]
![IMG_0286](https://user-images.githubusercontent.com/31007683/183759188-9102e33a-700c-419a-9f04-e27fdeccaf6c.PNG)
Like you can see in this image, I was able to add some color to the blurred view. Just keep in mind that the applied color can be a bit faint, this is because filling it with a color will make the view behind it invisible to see.

**Comment by vanwijkdave** [comment]
Closing the issue due to: I think everything is fixed now! Will appear next update :)
