### ISSUE TITLE
Crashed when selecting app to open

### ISSUE THREAD

**Issue by Louiswu2011** [vanwijkdave/Ainsworth-Issues#31]
Settings app crashed when selecting app to open in device option.
However no crash log appear in cr4shed.
Tried downgrading libmryipc but no luck.
I'm on iOS 14.4, iPhone 11 Pro.

**Comment by vanwijkdave** [comment]
Sorry for the delay! If you are still using the tweak, is the issue still present?

**Comment by vanwijkdave** [comment]
Closed due to no answer
