### ISSUE TITLE
Tweak unusable as settings don't work!

### ISSUE THREAD

**Issue by Dansco** [vanwijkdave/Ainsworth-Issues#32]
Bought this for my iPhone x on iOS 14.3 with Unc0ver 7.0.2

![image](https://user-images.githubusercontent.com/6923435/147987828-6e37228b-5dfb-4c21-a554-50fb7a760f44.jpeg)

This first image is what happens when you opening tweak settings

![image](https://user-images.githubusercontent.com/6923435/147987905-6d98cc1a-9724-4ced-acb8-bc613cd2077d.jpeg)

This second one is what the settings look now. Useless! 

Any ideas for a fix???

**Comment by dicksonboy** [comment]
i have this too, but thia is after i upgrade to iOS14.8

**Comment by Dansco** [comment]
The dev reached out and the issue is fixed. Turns out (for me) the issue was with Shuffle tweak. Disable that and it works fine. Set the tweak up and enable Shuffle again. 
Hope this helps.
