### ISSUE TITLE
I purchased the tweak but it’s says I didn’t

### ISSUE THREAD

**Issue by SlippySkip** [vanwijkdave/Ainsworth-Issues#34]
Hi, so I purchased the tweak on twickd and recently they have been up and down. So maybe that’s the problem but the tweak says I did not purchase the tweak. I included some photos.
![D2D6D8F2-0A59-48E1-A2E6-6888915BA49C](https://user-images.githubusercontent.com/81676936/152071398-034ecb70-026c-45b2-8560-e3fc52a9d01b.jpeg)
![4483DAB6-61A2-48BA-B46B-69481422D957](https://user-images.githubusercontent.com/81676936/152071399-76a41d21-83f7-4166-96cb-8db26cd76381.jpeg)
![2116E816-3802-47C4-8264-A1A7C1DB80A5](https://user-images.githubusercontent.com/81676936/152071401-8f56445b-41c8-40ca-9544-61e2885e3f2e.jpeg)
![BE424256-5DC7-44AD-9A1B-22858118FFF1](https://user-images.githubusercontent.com/81676936/152071402-735950c3-8497-4456-9a5d-a594f210adaf.jpeg)

**Comment by vanwijkdave** [comment]
Next update has the licensing code rewritten, will prob. fix this issue!
