### ISSUE TITLE
Not enough libraries for Ainsworth tweak on rootless jailbreak

### ISSUE THREAD

**Issue by Cliemens** [vanwijkdave/Ainsworth-Issues#38]
Hello. Lack of libraries for Ainsworth tweak on rootless jailbreak or is it a tweak for regular jailbreaks?
![006F51D0-D7F4-4EC5-BDDB-8F4759C5D0F4](https://github.com/vanwijkdave/Ainsworth-Issues/assets/54388488/7e4f76b2-f6a5-44f4-80c6-b86ed8a62971)

**Comment by vanwijkdave** [comment]
Hi, try adding the following repo: https://sparkdev.me to Sileo

**Comment by Cliemens** [comment]
Thank you. This repository was not enough!
