### ISSUE TITLE
Seems to be installed but not (I can see the config). Can't reinstall because is not installed

### ISSUE THREAD

**Issue by vladmen01** [vanwijkdave/Ainsworth-Issues#6]
Hi Dave, I purchased your tweak, "installed", but nothing happened, don't search any device :(
I tried to reinstall but I can't because "is not installed", I say this because I can see in my settings the tweak but don't do it nothing. In Cydia I always have the button "Install" and show me this error:

_**APT had planned for dpkg to do more than it reported back (0 vs 5). Affected packages: com.twickd.dave-van-wijk.ainsworth:iphoneos-arm**_  

Thanks, for your help. 

P. S. I'm trying to connect my Sony WH-1000X3 with you awesome tweak.

**Comment by vanwijkdave** [comment]
Should work now 🙂
