### ISSUE TITLE
Displays improperly in landscape on iPad

### ISSUE THREAD

**Issue by Iristallite** [vanwijkdave/Ainsworth-Issues#9]
this does not look right
![80212C34-B61A-4998-964A-A17954F21C0F](https://user-images.githubusercontent.com/28459742/83319780-054df300-a21c-11ea-9883-9f2a2f7c340a.png)

**Comment by vanwijkdave** [comment]
Added to next version requests!

**Comment by Iristallite** [comment]
and now it's upside down
![813176DD-AC1C-4C5E-B74F-9BDDDFA94A3E](https://user-images.githubusercontent.com/28459742/83355548-ac28b100-a33a-11ea-8ce2-4b7a90fddc2f.png)

**Comment by Iristallite** [comment]
fixed in 1.2.2
